// ─────────────────────────────────────────────────────────────────────────────
// Privacy Policy — Content Data
//
// HOW TO UPDATE:
//   • New mobile app?             → Add an entry to APP_DATA_COLLECTION with type: 'Mobile App'.
//   • New mobile feature?         → Add an entry with type: 'Feature'.
//   • New cookie type?            → Add a row to COOKIE_TYPES.
//   • New CCPA category?          → Add a row to CCPA_CATEGORIES.
//   • New third-party provider?   → Add an entry to THIRD_PARTY_PROVIDERS.
//   • New definition?             → Add an entry to DEFINITIONS.
//
// NOTE: Only 'Mobile App' and 'Feature' entries are shown in Section 2.
// Web apps and websites are intentionally excluded from this policy.
// The page component reads these arrays and renders them automatically.
// No JSX changes are required.
// ─────────────────────────────────────────────────────────────────────────────

export const LAST_UPDATED = 'July 14, 2025'

// ── Definitions ───────────────────────────────────────────────────────────────

export const DEFINITIONS: { term: string; def: string }[] = [
  { term: 'Account',              def: 'A unique account created for You to access our Service or parts of our Service.' },
  { term: 'Affiliate',            def: 'An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.' },
  { term: 'Business',             def: "For the purpose of CCPA/CPRA, the Company as the legal entity that collects Consumers' personal information and determines the purposes and means of its processing." },
  { term: 'CCPA / CPRA',          def: 'The California Consumer Privacy Act as amended by the California Privacy Rights Act of 2020.' },
  { term: 'Company',              def: 'Arjava Technologies (ARJAVA INDIA TECH PRIVATE LIMITED), 2135 204th PL NE, Sammamish, WA 98074. For the purpose of the GDPR, the Company is the Data Controller.' },
  { term: 'Consumer',             def: 'For the purpose of the CCPA/CPRA, a natural person who is a California resident.' },
  { term: 'Cookies',              def: 'Small files placed on Your device by a website, containing details of Your browsing history on that website among other uses.' },
  { term: 'Country',              def: 'United States of America.' },
  { term: 'Data Controller',      def: 'For the purposes of the GDPR, the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.' },
  { term: 'Device',               def: 'Any device that can access the Service, such as a computer, mobile phone, or digital tablet.' },
  { term: 'Do Not Track (DNT)',   def: 'A concept promoted by US regulatory authorities for the Internet industry to develop a mechanism allowing users to control the tracking of their online activities across websites.' },
  { term: 'GDPR',                 def: 'EU General Data Protection Regulation.' },
  { term: 'Personal Data',        def: 'Any information that relates to an identified or identifiable individual. Under GDPR this includes name, identification number, location data, or online identifier. Under CCPA/CPRA it means any information that identifies, relates to, or could reasonably be linked with You.' },
  { term: 'Service',              def: 'Refers to the Website.' },
  { term: 'Service Provider',     def: 'Any natural or legal person who processes data on behalf of the Company, including third-party companies or individuals employed to facilitate, provide, or analyze the Service. Under GDPR, Service Providers are considered Data Processors.' },
  { term: 'Usage Data',           def: 'Data collected automatically, either generated by use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
  { term: 'Website',              def: 'Arjava, accessible from https://arjavatech.com' },
  { term: 'You',                  def: 'The individual accessing or using the Service, or the company or other legal entity on whose behalf such individual is accessing or using the Service. Under GDPR, You may be referred to as the Data Subject or User.' },
]

// ── Per-application / per-feature data collection ────────────────────────────
//
// Each entry represents one application or feature.
// Add a new object here whenever a new product or feature collects user data.

export type DataField = {
  label: string        // Name of the data type, e.g. "Email Address"
  purpose: string      // Why it is collected
  storage: string      // Where it is stored, e.g. "Server" | "Device only" | "Third-party"
  sharedWith: string   // Who it is shared with, or "No third parties"
}

export type AppType = 'Mobile App' | 'Web App' | 'Website' | 'Feature'

export type AppDataEntry = {
  app: string          // Application or feature name
  type: AppType        // Category — only 'Mobile App' and 'Feature' appear in the policy
  appUrl?: string      // Public URL of the application, if applicable
  description: string  // One-line description of the app / feature
  purposes: string[]   // List of purposes for which the app is used
  fields: DataField[]
}

export const APP_DATA_COLLECTION: AppDataEntry[] = [

  // ── 1. Tap Time ──────────────────────────────────────────────────────────────
  {
    app: 'Tap Time',
    type: 'Mobile App',
    appUrl: 'https://tap-time.com',
    description: 'Employee time and attendance tracking mobile app available on iOS and Android.',
    purposes: [
      'To enable employees to check in and out with real-time attendance tracking across all devices.',
      'To provide managers with daily and salary-based attendance reports.',
      'To support full employee management with role-based access control.',
      'To facilitate payroll processing and workforce scheduling.',
    ],
    fields: [
      { label: 'Device ID',                                                               purpose: 'Device identification for secure check-in/check-out session management.',                storage: 'Server',                                    sharedWith: 'No third parties' },
      { label: 'Camera (used for check-in and check-out)',                                purpose: 'Capturing a photo at the time of check-in and check-out to verify employee presence.',  storage: 'Server',                                    sharedWith: 'Employer / Organization administrator' },
    ],
  },

  // ── 2. Bright Brains ─────────────────────────────────────────────────────────
  {
    app: 'Bright Brains',
    type: 'Mobile App',
    appUrl: 'http://bright-brains.net',
    description: 'Brain training mobile app with cognitive games and memory challenges, available on iOS and Android.',
    purposes: [
      'To deliver brain training games, memory exercises, and cognitive challenges to users.',
      'To track individual progress and performance across training sessions.',
      'To personalize the training experience based on user performance history.',
    ],
    fields: [
      { label: 'Email Address',                                                           purpose: 'Account creation and login.',                                                           storage: 'Server',                                    sharedWith: 'No third parties' },
    ],
  },

  // ── 3. Rattham Udhavi ────────────────────────────────────────────────────────
  {
    app: 'Rattham Udhavi',
    type: 'Mobile App',
    appUrl: undefined,
    description: 'Blood donation management app connecting donors with recipients and blood banks, available on Android.',
    purposes: [
      'To register blood donors and maintain a searchable donor database.',
      'To connect recipients with compatible donors during emergencies.',
      'To manage blood bank inventory and operations.',
      'To send mobile notifications for urgent blood requests.',
    ],
    fields: [
      { label: 'Full Name',                                                               purpose: 'Donor registration and identity verification.',                                         storage: 'Server',                                    sharedWith: 'Blood banks and verified recipients (on request)' },
      { label: 'Blood Group',                                                             purpose: 'Matching donors with compatible recipients.',                                           storage: 'Server',                                    sharedWith: 'Blood banks and verified recipients (on request)' },
      { label: 'Contact Number',                                                          purpose: 'Coordinating between donors, recipients, and blood banks.',                            storage: 'Server',                                    sharedWith: 'Blood banks and verified recipients (on request)' },
      { label: 'Location Data (city or region)',                                          purpose: 'Matching donors with nearby recipients and blood banks.',                               storage: 'Server',                                    sharedWith: 'Blood banks and verified recipients (on request)' },
    ],
  },

  // ── 4. Element Explorer ──────────────────────────────────────────────────────
  {
    app: 'Element Explorer',
    type: 'Mobile App',
    appUrl: 'https://element-explorer.com',
    description: 'Interactive periodic table and chemistry learning mobile app available on iOS and Android.',
    purposes: [
      'To provide an interactive and educational experience for exploring chemical elements.',
      'To support students and educators with detailed element data and properties.',
    ],
    fields: [],
  },

  // ── 5. FindBed ───────────────────────────────────────────────────────────────
  {
    app: 'FindBed',
    type: 'Mobile App',
    appUrl: undefined,
    description: 'Healthcare bed booking platform connecting patients with available hospital beds in real-time across India.',
    purposes: [
      'To display real-time hospital bed availability to patients and caregivers.',
      'To facilitate bed booking and reservation for patients.',
      'To support emergency services by connecting patients with the nearest available beds.',
    ],
    fields: [
      { label: 'Patient Name and Contact Information',                                    purpose: 'Bed booking, reservation confirmation, and hospital coordination.',                     storage: 'Server',                                    sharedWith: 'Relevant hospital or healthcare facility' },
      { label: 'Location Data',                                                           purpose: 'Identifying nearby hospitals with available beds.',                                     storage: 'Server',                                    sharedWith: 'No third parties' },
      { label: 'Medical Requirement Details (bed type, urgency)',                         purpose: 'Matching patients with appropriate bed availability.',                                  storage: 'Server',                                    sharedWith: 'Relevant hospital or healthcare facility' },
    ],
  },

  // ── 6. Sehatuka ──────────────────────────────────────────────────────────────
  {
    app: 'Sehatuka',
    type: 'Mobile App',
    appUrl: undefined,
    description: 'Medicare app for medical checkups, medicine reminders, doctor appointments, and health records on Android and iOS.',
    purposes: [
      'To send timely reminders for medications, checkups, and doctor appointments.',
      'To maintain a personal health record for the user.',
      'To help users manage and track their overall health and wellness.',
    ],
    fields: [
      { label: 'Name, Age, and Gender',                                                   purpose: 'Personalized health tracking and reminder scheduling.',                                 storage: 'Server',                                    sharedWith: 'No third parties' },
      { label: 'Health Records (medications, appointments, checkup history)',             purpose: 'Health record management and reminder generation.',                                     storage: 'Server (encrypted)',                        sharedWith: 'No third parties' },
      { label: 'Device Identifiers',                                                      purpose: 'Push notification delivery for reminders.',                                            storage: 'Server',                                    sharedWith: 'Firebase Cloud Messaging' },
    ],
  },

  // ── 7. StockBrains.ai ────────────────────────────────────────────────────────
  {
    app: 'StockBrains.ai',
    type: 'Mobile App',
    appUrl: undefined,
    description: 'AI-powered stock research app with SWOT analysis, market insights, and investment analytics.',
    purposes: [
      'To provide AI-driven stock research, SWOT analysis, and market insights to users.',
      'To support data-driven investment decision-making.',
      'To personalize market insights based on user watchlists and preferences.',
    ],
    fields: [
      { label: 'Email Address',                                                           purpose: 'Account creation and login.',                                                           storage: 'Server',                                    sharedWith: 'No third parties' },
      { label: 'Watchlist and Investment Preferences',                                    purpose: 'Personalized stock recommendations and alerts.',                                        storage: 'Server',                                    sharedWith: 'No third parties' },
      { label: 'Usage Data and In-App Interactions',                                      purpose: 'App performance monitoring and feature improvement.',                                   storage: 'Server / Analytics provider',               sharedWith: 'Firebase' },
    ],
  },

  // ── 8. Facial Recognition Feature ───────────────────────────────────────────
  {
    app: 'Facial Recognition Feature',
    type: 'Feature',
    appUrl: undefined,
    description: 'An optional on-device capability available within select Arjava applications.',
    purposes: [
      'To authenticate users securely without transmitting biometric data over the network.',
      'To personalize the application experience based on the recognized user profile.',
    ],
    fields: [
      { label: 'Camera Feed & Facial Recognition Data',                                   purpose: 'Client-side user authentication and personalization only.',                             storage: 'Device only — never transmitted to servers', sharedWith: 'No third parties' },
    ],
  },

  // ── Add new mobile applications below ────────────────────────────────────────
  // {
  //   app: 'My New Mobile App',
  //   type: 'Mobile App',
  //   appUrl: 'https://example.arjavatech.com',   // optional, set undefined if not yet live
  //   description: 'Short description of what the app does.',
  //   purposes: [
  //     'Primary purpose of the application.',
  //     'Secondary purpose, if any.',
  //   ],
  //   fields: [
  //     { label: 'Data type collected', purpose: 'Why it is collected', storage: 'Where it is stored', sharedWith: 'Who it is shared with' },
  //   ],
  // },
]

// ── Cookie types ──────────────────────────────────────────────────────────────

export const COOKIE_TYPES: { name: string; persistence: string; purpose: string }[] = [
  { name: 'Necessary / Essential',    persistence: 'Session',    purpose: 'Essential to provide services available through the Website and to enable core features.' },
  { name: 'Cookie Policy Acceptance', persistence: 'Persistent', purpose: 'Identifies whether users have accepted the use of cookies on the Website.' },
  { name: 'Functionality',            persistence: 'Persistent', purpose: 'Remembers choices You make when using the Website, such as language or region preferences.' },
  { name: 'Tracking & Performance',   persistence: 'Persistent', purpose: 'Tracks traffic information and how users interact with the Website to improve performance.' },
  { name: 'Targeting & Advertising',  persistence: 'Persistent', purpose: 'Tracks browsing habits to enable delivery of advertising more relevant to You.' },
]

// ── Third-party service providers ─────────────────────────────────────────────

export const THIRD_PARTY_PROVIDERS: { name: string; description: string; policyUrl: string }[] = [
  { name: 'Google Analytics', description: 'Tracks and reports website traffic.',          policyUrl: 'https://policies.google.com/privacy' },
  { name: 'Firebase',         description: 'Analytics service provided by Google Inc.',    policyUrl: 'https://policies.google.com/privacy' },
]

// ── CCPA categories ───────────────────────────────────────────────────────────

export const CCPA_CATEGORIES: { cat: string; ex: string }[] = [
  { cat: 'A — Identifiers',                  ex: 'Real name, alias, postal address, unique personal identifier, online identifier, IP address, email address, account name.' },
  { cat: 'B — California Customer Records',  ex: 'Name, signature, Social Security number, physical characteristics or description, address, telephone number.' },
  { cat: 'F — Internet / Network Activity',  ex: 'Interaction with our Service or advertisements.' },
  { cat: 'G — Geolocation Data',               ex: 'Precise or approximate physical location derived from GPS or IP address, used for service personalization and analytics.' },
  { cat: 'L — Sensitive Personal Information',  ex: 'Account login credentials, geolocation data.' },
]

// ── GDPR rights ───────────────────────────────────────────────────────────────

export const GDPR_RIGHTS: { right: string; description: string }[] = [
  { right: 'Right of Access',           description: 'Request access to, update, or deletion of the Personal Data We hold about You.' },
  { right: 'Right to Rectification',    description: 'Request correction of any incomplete or inaccurate Personal Data We hold about You.' },
  { right: 'Right to Object',           description: 'Object to Our processing of Your Personal Data where We rely on a legitimate interest as the legal basis.' },
  { right: 'Right to Erasure',          description: 'Request deletion of Your Personal Data when there is no compelling reason for Us to continue processing it.' },
  { right: 'Right to Data Portability', description: 'Receive Your Personal Data in a structured, commonly used, machine-readable format, or request its transfer to a third party of Your choice.' },
  { right: 'Right to Withdraw Consent', description: 'Withdraw Your consent to the processing of Your Personal Data at any time.' },
]

// ── CCPA rights ───────────────────────────────────────────────────────────────

export const CCPA_RIGHTS: { right: string; description: string }[] = [
  { right: 'Right to Notice',            description: 'Be informed of the categories of Personal Data being collected and the purposes for which it is used.' },
  { right: 'Right to Know / Access',     description: 'Request disclosure of Our collection, use, sale, and sharing of Your personal information.' },
  { right: 'Right to Opt-Out',           description: 'Direct Us not to sell or share Your personal information with third parties.' },
  { right: 'Right to Correct',           description: 'Request correction of inaccurate personal information We hold about You.' },
  { right: 'Right to Delete',            description: 'Request deletion of Your Personal Data, subject to certain exceptions.' },
  { right: 'Right to Non-Discrimination', description: 'Not be discriminated against for exercising any of Your CCPA/CPRA rights.' },
]

// ── Data use purposes ─────────────────────────────────────────────────────────

export const DATA_USE_PURPOSES: { bold: string; rest: string }[] = [
  { bold: 'To provide and maintain our Service',  rest: ', including monitoring usage and performance.' },
  { bold: 'To manage Your Account',               rest: ': to manage Your registration as a user of the Service.' },
  { bold: 'For the performance of a contract',    rest: ': to fulfill the purchase contract for products, items, or services You have requested.' },
  { bold: 'To contact You',                       rest: ': via email, telephone, SMS, or other electronic communication regarding updates or informative notices related to the Service.' },
  { bold: 'To provide You with news and offers',  rest: ': about other goods, services, and events we offer that may be of interest to You.' },
  { bold: 'To manage Your requests',              rest: ': to attend to and manage requests You submit to Us.' },
  { bold: 'For business transfers',               rest: ': to evaluate or conduct a merger, acquisition, restructuring, or other transfer of some or all of Our assets.' },
  { bold: 'For analytics and improvement',        rest: ': data analysis, identifying usage trends, and measuring the effectiveness of our promotional campaigns.' },
]

// ── Data sharing circumstances ────────────────────────────────────────────────

export const DATA_SHARING: { bold: string; rest: string }[] = [
  { bold: 'With Service Providers', rest: ': to monitor and analyze the use of our Service on our behalf.' },
  { bold: 'For business transfers', rest: ': in connection with any merger, sale of Company assets, financing, or acquisition.' },
  { bold: 'With Affiliates',        rest: ': who are required to honor this Privacy Policy.' },
  { bold: 'With business partners', rest: ': to offer You certain products, services, or promotions.' },
  { bold: 'With other users',       rest: ': when You voluntarily share personal information in public areas of the Service.' },
  { bold: 'With Your consent',      rest: ': for any other purpose with Your explicit consent.' },
]

// ── Legal disclosure reasons ──────────────────────────────────────────────────

export const LEGAL_DISCLOSURE_REASONS: string[] = [
  'Comply with a legal obligation',
  'Protect and defend the rights or property of the Company',
  'Prevent or investigate possible wrongdoing in connection with the Service',
  'Protect the personal safety of users of the Service or the public',
  'Protect against legal liability',
]

// ── Contact information ───────────────────────────────────────────────────────

export const CONTACT_INFO = {
  company:  'Arjava Technologies',
  address:  '2135 204th PL NE, Sammamish, WA 98074',
  phone:    '+1 (425) 999-9719',
  phoneHref: 'tel:+14259999719',
  email:    'arjavatech@gmail.com',
  emailHref: 'mailto:arjavatech@gmail.com',
}
