import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import PageHero from '@/components/ui/PageHero'
import AnimatedSection from '@/components/ui/AnimatedSection'
import PageTransition from '@/components/ui/PageTransition'

// ── Typographic helpers ──────────────────────────────────────────────────────

const H2 = ({ children }: { children: React.ReactNode }) => (
  <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-teal-400 mt-10 mb-3 pb-2 border-b border-slate-700">
    {children}
  </h2>
)

const H3 = ({ children }: { children: React.ReactNode }) => (
  <h3 className="text-sm sm:text-base md:text-lg font-semibold text-white mt-6 mb-2">
    {children}
  </h3>
)

const H4 = ({ children }: { children: React.ReactNode }) => (
  <h4 className="text-sm sm:text-base font-semibold text-slate-300 mt-4 mb-2">
    {children}
  </h4>
)

const P = ({ children }: { children: React.ReactNode }) => (
  <p className="text-sm md:text-base text-slate-400 leading-relaxed mb-4">{children}</p>
)

const Ul = ({ children }: { children: React.ReactNode }) => (
  <ul className="pl-5 space-y-2 text-slate-400 text-xs sm:text-sm leading-relaxed mb-5">
    {children}
  </ul>
)

const Li = ({ children }: { children: React.ReactNode }) => (
  <li className="flex gap-2">
    <span className="text-teal-400 shrink-0 mt-0.5">›</span>
    <span>{children}</span>
  </li>
)

// ── Static data ──────────────────────────────────────────────────────────────

const DEFINITIONS: { term: string; def: React.ReactNode }[] = [
  { term: 'Account', def: 'A unique account created for You to access our Service or parts of our Service.' },
  { term: 'Affiliate', def: 'An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.' },
  { term: 'Business', def: 'For the purpose of CCPA/CPRA, the Company as the legal entity that collects Consumers\' personal information and determines the purposes and means of its processing.' },
  { term: 'CCPA / CPRA', def: 'The California Consumer Privacy Act as amended by the California Privacy Rights Act of 2020.' },
  { term: 'Company', def: 'Arjava Technologies (ARJAVA INDIA TECH PRIVATE LIMITED), 2135 204th PL NE, Sammamish, WA 98074. For the purpose of the GDPR, the Company is the Data Controller.' },
  { term: 'Consumer', def: 'For the purpose of the CCPA/CPRA, a natural person who is a California resident.' },
  { term: 'Cookies', def: 'Small files placed on Your device by a website, containing details of Your browsing history on that website among other uses.' },
  { term: 'Country', def: 'United States of America.' },
  { term: 'Data Controller', def: 'For the purposes of the GDPR, the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.' },
  { term: 'Device', def: 'Any device that can access the Service, such as a computer, mobile phone, or digital tablet.' },
  { term: 'Do Not Track (DNT)', def: 'A concept promoted by US regulatory authorities for the Internet industry to develop a mechanism allowing users to control the tracking of their online activities across websites.' },
  { term: 'GDPR', def: 'EU General Data Protection Regulation.' },
  { term: 'Personal Data', def: 'Any information that relates to an identified or identifiable individual. Under GDPR this includes name, identification number, location data, or online identifier. Under CCPA/CPRA it means any information that identifies, relates to, or could reasonably be linked with You.' },
  { term: 'Service', def: 'Refers to the Website.' },
  { term: 'Service Provider', def: 'Any natural or legal person who processes data on behalf of the Company, including third-party companies or individuals employed to facilitate, provide, or analyze the Service. Under GDPR, Service Providers are considered Data Processors.' },
  { term: 'Usage Data', def: 'Data collected automatically, either generated by use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
  {
    term: 'Website',
    def: (
      <>
        Arjava, accessible from{' '}
        <a href="https://arjavatech.com" target="_blank" rel="noreferrer" className="text-teal-400 hover:underline">
          https://arjavatech.com
        </a>
      </>
    ),
  },
  { term: 'You', def: 'The individual accessing or using the Service, or the company or other legal entity on whose behalf such individual is accessing or using the Service. Under GDPR, You may be referred to as the Data Subject or User.' },
]

const COOKIE_TYPES = [
  { name: 'Necessary / Essential', persistence: 'Session', purpose: 'Essential to provide services available through the Website and to enable core features.' },
  { name: 'Cookie Policy Acceptance', persistence: 'Persistent', purpose: 'Identifies whether users have accepted the use of cookies on the Website.' },
  { name: 'Functionality', persistence: 'Persistent', purpose: 'Remembers choices You make when using the Website, such as language or region preferences.' },
  { name: 'Tracking & Performance', persistence: 'Persistent', purpose: 'Tracks traffic information and how users interact with the Website to improve performance.' },
  { name: 'Targeting & Advertising', persistence: 'Persistent', purpose: 'Tracks browsing habits to enable delivery of advertising more relevant to You.' },
]

const CCPA_CATEGORIES = [
  { cat: 'A — Identifiers', ex: 'Real name, alias, postal address, unique personal identifier, online identifier, IP address, email address, account name.' },
  { cat: 'B — California Customer Records', ex: 'Name, signature, Social Security number, physical characteristics or description, address, telephone number.' },
  { cat: 'F — Internet / Network Activity', ex: 'Interaction with our Service or advertisements.' },
  { cat: 'L — Sensitive Personal Information', ex: 'Account login credentials, geolocation data.' },
]

// ── Reusable table component ─────────────────────────────────────────────────

function DataTable({ headers, rows }: { headers: string[]; rows: (string | React.ReactNode)[][] }) {
  return (
    <div className="overflow-x-auto mb-6">
      <table className="w-full text-xs sm:text-sm border-collapse">
        <thead>
          <tr className="border-b border-slate-700">
            {headers.map((h) => (
              <th key={h} className="text-left text-white font-semibold py-2 pr-4">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-b border-slate-800">
              {row.map((cell, j) => (
                <td key={j} className={`py-2 pr-4 align-top ${j === 0 ? 'text-teal-400 font-medium' : 'text-slate-400'}`}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ── Page component ───────────────────────────────────────────────────────────

export default function PrivacyPolicyPage2() {
  return (
    <PageTransition>
      <Navbar />
      <PageHero
        title="Privacy Policy"
        subtitle="How we collect, use, and protect your information."
        breadcrumb="Privacy Policy"
      />

      <section className="bg-dark-base py-10 md:py-16">
        <div className="container mx-auto px-4 sm:px-6 max-w-4xl">
          <AnimatedSection>
            <div className="card-dark p-5 sm:p-8 md:p-10">

              <p className="text-xs text-slate-500 mb-6">Last updated: October 1, 2025</p>

              {/* ── Introduction ── */}
              <P>
                This Privacy Policy describes the policies and procedures of Arjava Technologies
                ("Company", "We", "Us", or "Our") on the collection, use, and disclosure of Your
                information when You use our Service. It also informs You of Your privacy rights and
                how the law protects You.
              </P>
              <P>
                We use Your Personal Data to provide and improve the Service. By using the Service,
                You agree to the collection and use of information in accordance with this Privacy Policy.
              </P>

              {/* ── 1. Interpretation and Definitions ── */}
              <H2>1. Interpretation and Definitions</H2>

              <H3>Interpretation</H3>
              <P>
                Words with an initial capital letter have meanings defined under the following
                conditions. These definitions apply equally whether the terms appear in singular or
                plural form.
              </P>

              <H3>Definitions</H3>
              <P>For the purposes of this Privacy Policy:</P>
              <dl className="space-y-3 mb-6">
                {DEFINITIONS.map(({ term, def }) => (
                  <div key={term} className="grid grid-cols-[minmax(0,auto)_1fr] gap-x-4 text-xs sm:text-sm">
                    <dt className="font-semibold text-teal-400 whitespace-nowrap">{term}</dt>
                    <dd className="text-slate-400 leading-relaxed">{def}</dd>
                  </div>
                ))}
              </dl>

              {/* ── 2. Collecting and Using Your Personal Data ── */}
              <H2>2. Collecting and Using Your Personal Data</H2>

              <H3>Types of Data Collected</H3>

              <H4>Personal Data</H4>
              <P>
                While using Our Service, We may ask You to provide certain personally identifiable
                information that can be used to contact or identify You. This may include, but is not
                limited to:
              </P>
              <Ul>
                <Li><strong>Email address</strong></Li>
                <Li>
                  <span>
                    <strong>Camera Access — </strong>
                    Our application requests access to the device camera solely to enable facial
                    recognition for client-side operations such as user authentication or
                    personalization. Images and facial recognition data are stored only on the local
                    device and are never transmitted to or stored on our servers, nor shared with any
                    third party.
                  </span>
                </Li>
                <Li><strong>Usage Data</strong></Li>
              </Ul>

              <H4>Usage Data</H4>
              <P>Usage Data is collected automatically when You use the Service and may include:</P>
              <Ul>
                <Li>Your device's Internet Protocol (IP) address, browser type, and browser version</Li>
                <Li>Pages of our Service You visit, the time and date of Your visit, and time spent on those pages</Li>
                <Li>Unique device identifiers and other diagnostic data</Li>
                <Li>When accessing via a mobile device: device type, unique mobile device ID, mobile operating system, and mobile browser type</Li>
              </Ul>

              <H4>Tracking Technologies and Cookies</H4>
              <P>
                We use Cookies and similar tracking technologies (beacons, tags, and scripts) to
                track activity on Our Service and store certain information. Cookies may be
                "Session Cookies" (deleted when You close Your browser) or "Persistent Cookies"
                (remaining on Your device until they expire or You delete them).
              </P>
              <DataTable
                headers={['Cookie Type', 'Persistence', 'Purpose']}
                rows={COOKIE_TYPES.map(({ name, persistence, purpose }) => [name, persistence, purpose])}
              />
              <P>
                You can instruct Your browser to refuse all Cookies or to notify You when a Cookie
                is being sent. However, declining Cookies may limit Your ability to use certain
                features of our Service.
              </P>

              <H3>Use of Your Personal Data</H3>
              <P>The Company may use Personal Data for the following purposes:</P>
              <Ul>
                {[
                  ['To provide and maintain our Service', ', including monitoring usage and performance.'],
                  ['To manage Your Account', ': to manage Your registration as a user of the Service.'],
                  ['For the performance of a contract', ': to fulfill the purchase contract for products, items, or services You have requested.'],
                  ['To contact You', ': via email, telephone, SMS, or other electronic communication regarding updates or informative notices related to the Service.'],
                  ['To provide You with news and offers', ': about other goods, services, and events we offer that may be of interest to You.'],
                  ['To manage Your requests', ': to attend to and manage requests You submit to Us.'],
                  ['For business transfers', ': to evaluate or conduct a merger, acquisition, restructuring, or other transfer of some or all of Our assets.'],
                  ['For analytics and improvement', ': data analysis, identifying usage trends, and measuring the effectiveness of our promotional campaigns.'],
                ].map(([bold, rest]) => (
                  <Li key={bold}><strong>{bold}</strong>{rest}</Li>
                ))}
              </Ul>

              <H3>Sharing Your Personal Data</H3>
              <P>We may share Your personal information in the following circumstances:</P>
              <Ul>
                {[
                  ['With Service Providers', ': to monitor and analyze the use of our Service on our behalf.'],
                  ['For business transfers', ': in connection with any merger, sale of Company assets, financing, or acquisition.'],
                  ['With Affiliates', ': who are required to honor this Privacy Policy.'],
                  ['With business partners', ': to offer You certain products, services, or promotions.'],
                  ['With other users', ': when You voluntarily share personal information in public areas of the Service.'],
                  ['With Your consent', ': for any other purpose with Your explicit consent.'],
                ].map(([bold, rest]) => (
                  <Li key={bold}><strong>{bold}</strong>{rest}</Li>
                ))}
              </Ul>

              <H3>Retention of Your Personal Data</H3>
              <P>
                The Company retains Your Personal Data only for as long as necessary for the purposes
                set out in this Privacy Policy, and to the extent necessary to comply with legal
                obligations, resolve disputes, and enforce our agreements and policies. Usage Data is
                generally retained for a shorter period, except where it is used to strengthen
                security or improve the functionality of Our Service.
              </P>

              <H3>Transfer of Your Personal Data</H3>
              <P>
                Your information, including Personal Data, may be processed at the Company's operating
                offices or in any other location where the parties involved in processing are located.
                This may involve transfer to computers outside Your state, province, country, or other
                governmental jurisdiction where data protection laws may differ from those in Your
                jurisdiction. Your consent to this Privacy Policy represents Your agreement to that
                transfer. The Company will take all steps reasonably necessary to ensure Your data is
                treated securely and in accordance with this Privacy Policy.
              </P>

              <H3>Deletion of Your Personal Data</H3>
              <P>
                You have the right to request deletion of the Personal Data We hold about You. You
                may update or delete Your information at any time through Your Account settings, or
                by contacting Us directly. Please note that We may need to retain certain information
                where We have a legal obligation or lawful basis to do so.
              </P>

              <H3>Disclosure of Your Personal Data</H3>
              <H4>Business Transactions</H4>
              <P>
                If the Company is involved in a merger, acquisition, or asset sale, Your Personal
                Data may be transferred. We will provide notice before Your Personal Data becomes
                subject to a different Privacy Policy.
              </P>
              <H4>Law Enforcement</H4>
              <P>
                Under certain circumstances, the Company may be required to disclose Your Personal
                Data if required to do so by law or in response to valid requests by public
                authorities (e.g., a court or government agency).
              </P>
              <H4>Other Legal Requirements</H4>
              <P>The Company may disclose Your Personal Data in the good-faith belief that such action is necessary to:</P>
              <Ul>
                {[
                  'Comply with a legal obligation',
                  'Protect and defend the rights or property of the Company',
                  'Prevent or investigate possible wrongdoing in connection with the Service',
                  'Protect the personal safety of users of the Service or the public',
                  'Protect against legal liability',
                ].map((item) => <Li key={item}>{item}</Li>)}
              </Ul>

              <H3>Security of Your Personal Data</H3>
              <P>
                The security of Your Personal Data is important to Us. We strive to use commercially
                acceptable means to protect Your Personal Data; however, no method of transmission
                over the Internet or method of electronic storage is 100% secure, and We cannot
                guarantee absolute security.
              </P>

              {/* ── 3. Third-Party Service Providers ── */}
              <H2>3. Third-Party Service Providers</H2>
              <P>
                The Service Providers We use may have access to Your Personal Data. These third-party
                vendors collect, store, use, process, and transfer information about Your activity on
                Our Service in accordance with their own Privacy Policies.
              </P>
              <H3>Analytics</H3>
              <Ul>
                <Li>
                  <strong>Google Analytics</strong> — Tracks and reports website traffic.{' '}
                  <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer" className="text-teal-400 hover:underline">
                    Google Privacy Policy ↗
                  </a>
                </Li>
                <Li>
                  <strong>Firebase</strong> — Analytics service provided by Google Inc.{' '}
                  <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer" className="text-teal-400 hover:underline">
                    Google Privacy Policy ↗
                  </a>
                </Li>
              </Ul>

              {/* ── 4. GDPR Privacy Rights ── */}
              <H2>4. GDPR Privacy Rights (European Union)</H2>
              <P>
                If You are located within the European Union, the Company is committed to respecting
                the confidentiality of Your Personal Data and ensuring You can exercise the following
                rights:
              </P>
              <Ul>
                {[
                  ['Right of Access', ': Request access to, update, or deletion of the Personal Data We hold about You.'],
                  ['Right to Rectification', ': Request correction of any incomplete or inaccurate Personal Data We hold about You.'],
                  ['Right to Object', ': Object to Our processing of Your Personal Data where We rely on a legitimate interest as the legal basis.'],
                  ['Right to Erasure', ': Request deletion of Your Personal Data when there is no compelling reason for Us to continue processing it.'],
                  ['Right to Data Portability', ': Receive Your Personal Data in a structured, commonly used, machine-readable format, or request its transfer to a third party of Your choice.'],
                  ['Right to Withdraw Consent', ': Withdraw Your consent to the processing of Your Personal Data at any time.'],
                ].map(([bold, rest]) => (
                  <Li key={bold}><strong>{bold}</strong>{rest}</Li>
                ))}
              </Ul>
              <P>
                To exercise any of these rights, please contact Us. We may ask You to verify Your
                identity before responding. You also have the right to lodge a complaint with a Data
                Protection Authority regarding Our collection and use of Your Personal Data.
              </P>

              {/* ── 5. CCPA/CPRA Privacy Rights ── */}
              <H2>5. CCPA/CPRA Privacy Rights (California Residents)</H2>
              <P>
                This section supplements the information in Our Privacy Policy and applies solely to
                visitors, users, and others who reside in the State of California.
              </P>

              <H3>Categories of Personal Information Collected</H3>
              <DataTable
                headers={['Category', 'Examples']}
                rows={CCPA_CATEGORIES.map(({ cat, ex }) => [cat, ex])}
              />

              <H3>Your Rights under the CCPA/CPRA</H3>
              <Ul>
                {[
                  ['Right to Notice', ': Be informed of the categories of Personal Data being collected and the purposes for which it is used.'],
                  ['Right to Know / Access', ': Request disclosure of Our collection, use, sale, and sharing of Your personal information.'],
                  ['Right to Opt-Out', ': Direct Us not to sell or share Your personal information with third parties.'],
                  ['Right to Correct', ': Request correction of inaccurate personal information We hold about You.'],
                  ['Right to Delete', ': Request deletion of Your Personal Data, subject to certain exceptions.'],
                  ['Right to Non-Discrimination', ': Not be discriminated against for exercising any of Your CCPA/CPRA rights.'],
                ].map(([bold, rest]) => (
                  <Li key={bold}><strong>{bold}</strong>{rest}</Li>
                ))}
              </Ul>

              <H3>"Do Not Track" Policy (CalOPPA)</H3>
              <P>
                Our Service does not respond to Do Not Track signals. However, some third-party
                websites do track browsing activities. You can set Your browser preferences to inform
                websites that You do not want to be tracked.
              </P>

              <H3>California's Shine the Light Law</H3>
              <P>
                Under California Civil Code Section 1798, California residents with an established
                business relationship with Us may request, once per year, information about sharing
                their Personal Data with third parties for those parties' direct marketing purposes.
              </P>

              <H3>California Privacy Rights for Minor Users</H3>
              <P>
                Under California Business and Professions Code Section 22581, California residents
                under the age of 18 who are registered users of online sites, services, or
                applications may request removal of content or information they have publicly posted.
              </P>

              {/* ── 6. Children's Privacy ── */}
              <H2>6. Children's Privacy</H2>
              <P>
                Our Service is not directed to anyone under the age of 13. We do not knowingly
                collect personally identifiable information from children under 13. If You are a
                parent or guardian and believe Your child has provided Us with Personal Data, please
                contact Us immediately so We can take appropriate action.
              </P>
              <P>
                Where We rely on consent as the legal basis for processing and Your country requires
                parental consent, We will obtain that consent before collecting or using the
                information.
              </P>

              {/* ── 7. Links to Other Websites ── */}
              <H2>7. Links to Other Websites</H2>
              <P>
                Our Service may contain links to third-party websites not operated by Us. Clicking a
                third-party link will direct You to that site. We strongly advise You to review the
                Privacy Policy of every site You visit. We have no control over, and assume no
                responsibility for, the content, privacy policies, or practices of any third-party
                sites or services.
              </P>

              {/* ── 8. Changes to This Privacy Policy ── */}
              <H2>8. Changes to This Privacy Policy</H2>
              <P>
                We may update this Privacy Policy from time to time. We will notify You of any
                material changes by posting the updated Privacy Policy on this page and, where
                appropriate, by sending You an email notification or displaying a prominent notice
                within Our Service prior to the change becoming effective. Continued use of the
                Service after changes are posted constitutes Your acceptance of the revised Policy.
              </P>

              {/* ── 9. Contact Us ── */}
              <H2>9. Contact Us</H2>
              <P>
                If You have any questions about this Privacy Policy or wish to exercise any of Your
                rights, please contact Us using the details below:
              </P>
              <div className="bg-dark-card border border-slate-700 rounded-lg p-5 space-y-2 text-sm">
                <p className="text-base font-semibold text-white">Arjava Technologies</p>
                <p className="text-slate-400">2135 204th PL NE, Sammamish, WA 98074</p>
                <p className="text-slate-400">
                  Phone:{' '}
                  <a href="tel:+14259999719" className="text-teal-400 hover:underline">
                    +1 (425) 999-9719
                  </a>
                </p>
                <p className="text-slate-400">
                  Email:{' '}
                  <a href="mailto:arjavatech@gmail.com" className="text-teal-400 hover:underline">
                    arjavatech@gmail.com
                  </a>
                </p>
              </div>

            </div>
          </AnimatedSection>
        </div>
      </section>

      <Footer />
    </PageTransition>
  )
}
