import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import PageHero from '@/components/ui/PageHero'
import AnimatedSection from '@/components/ui/AnimatedSection'
import PageTransition from '@/components/ui/PageTransition'

export default function PrivacyPolicy() {
  return (
    <PageTransition>
      <Navbar />
      <PageHero
        title="Privacy Policy"
        subtitle="How we collect, use, and protect your information."
        breadcrumb="Privacy Policy"
      />

      <section className="bg-dark-base py-16">
        <div className="container mx-auto px-6 max-w-4xl">
          <AnimatedSection>
            <div className="card-dark p-8 md:p-10">
              <p className="text-xs text-slate-500 mb-6">Last updated: October 14, 2023</p>

              <p className="text-slate-400 leading-relaxed mb-4">
                This Privacy Policy describes Our policies and procedures on the collection, use and
                disclosure of Your information when You use the Service and tells You about Your privacy
                rights and how the law protects You.
              </p>
              <p className="text-slate-400 leading-relaxed mb-8">
                We use Your Personal data to provide and improve the Service. By using the Service, You
                agree to the collection and use of information in accordance with this Privacy Policy.
              </p>

              {/* Section heading helper */}
              <h2 className="text-xl md:text-2xl font-bold text-teal-400 mb-4 mt-8">
                Interpretation and Definitions
              </h2>

              <h3 className="text-lg font-semibold text-white mb-2">Interpretation</h3>
              <p className="text-slate-400 leading-relaxed mb-6">
                The words of which the initial letter is capitalized have meanings defined under the
                following conditions. The following definitions shall have the same meaning regardless of
                whether they appear in singular or in plural.
              </p>

              <h3 className="text-lg font-semibold text-white mb-2">Definitions</h3>
              <p className="text-slate-400 mb-4">For the purposes of this Privacy Policy:</p>
              <ul className="space-y-3 text-slate-400 text-sm leading-relaxed mb-8">
                {[
                  {
                    term: 'Account',
                    def: 'A unique account created for You to access our Service or parts of our Service.',
                  },
                  {
                    term: 'Company',
                    def: '(referred to as "the Company", "We", "Us" or "Our") refers to Arjava India Tech Pvt Ltd, 19 Ganesh Nagar Main Road, Selaiyur, Chennai - 600073.',
                  },
                  {
                    term: 'Cookies',
                    def: 'Small files placed on Your device by a website, containing details of Your browsing history among other uses.',
                  },
                  {
                    term: 'Country',
                    def: 'Refers to: Tamil Nadu, India.',
                  },
                  {
                    term: 'Device',
                    def: 'Any device that can access the Service such as a computer, cellphone, or digital tablet.',
                  },
                  {
                    term: 'Personal Data',
                    def: 'Any information that relates to an identified or identifiable individual.',
                  },
                  {
                    term: 'Service',
                    def: 'Refers to the Website.',
                  },
                  {
                    term: 'Service Provider',
                    def: 'Any natural or legal person who processes the data on behalf of the Company.',
                  },
                  {
                    term: 'Usage Data',
                    def: 'Data collected automatically, generated by the use of the Service or from the Service infrastructure itself.',
                  },
                  {
                    term: 'Website',
                    def: (
                      <>
                        Refers to Arjava, accessible from{' '}
                        <a
                          href="https://arjavatech.com"
                          target="_blank"
                          rel="noreferrer"
                          className="text-teal-400 hover:underline"
                        >
                          https://arjavatech.com
                        </a>
                      </>
                    ),
                  },
                  {
                    term: 'You',
                    def: 'The individual accessing or using the Service.',
                  },
                ].map(({ term, def }) => (
                  <li key={term} className="flex gap-2">
                    <span className="text-teal-400 font-semibold min-w-fit">{term}:</span>
                    <span>{def}</span>
                  </li>
                ))}
              </ul>

              <h2 className="text-xl md:text-2xl font-bold text-teal-400 mb-4 mt-8">
                Collecting and Using Your Personal Data
              </h2>

              <h3 className="text-lg font-semibold text-white mb-2">Types of Data Collected</h3>

              <h4 className="text-base font-semibold text-slate-300 mb-2">Personal Data</h4>
              <p className="text-slate-400 leading-relaxed mb-3">
                While using Our Service, We may ask You to provide certain personally identifiable
                information that can be used to contact or identify You. This may include, but is not
                limited to:
              </p>
              <ul className="list-disc ml-6 space-y-1 text-slate-400 text-sm mb-6">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="text-base font-semibold text-slate-300 mb-2">Usage Data</h4>
              <p className="text-slate-400 leading-relaxed mb-8">
                Usage Data is collected automatically when using the Service and may include information
                such as Your Device's Internet Protocol address, browser type, browser version, the pages
                of our Service that You visit, the time and date of Your visit, the time spent on those
                pages, unique device identifiers and other diagnostic data.
              </p>

              <h3 className="text-lg font-semibold text-white mb-2">Use of Your Personal Data</h3>
              <p className="text-slate-400 leading-relaxed mb-3">
                The Company may use Personal Data for the following purposes:
              </p>
              <ul className="list-disc ml-6 space-y-2 text-slate-400 text-sm mb-8">
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To manage Your Account as a registered user of the Service.</li>
                <li>For the performance of a contract.</li>
                <li>To contact You with updates or informative communications.</li>
                <li>To provide You with news, special offers and general information.</li>
                <li>To manage Your requests to Us.</li>
              </ul>

              <h3 className="text-lg font-semibold text-white mb-2">Contact Us</h3>
              <p className="text-slate-400 leading-relaxed mb-3">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <ul className="list-disc ml-6 space-y-1 text-slate-400 text-sm">
                <li>
                  By email:{' '}
                  <a href="mailto:arjavatech@gmail.com" className="text-teal-400 hover:underline">
                    arjavatech@gmail.com
                  </a>
                </li>
                <li>By phone: 044-35675035</li>
              </ul>
            </div>
          </AnimatedSection>
        </div>
      </section>

      <Footer />
    </PageTransition>
  )
}
