import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import PageCover from '@/components/ui/PageCover'

export default function PrivacyPolicy() {
  return (
    <>
      <Navbar />
      <PageCover title="Privacy Policy" />

      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="border-[3px] border-blue-400 rounded-[15px] p-6 md:p-8">
          <p className="text-sm text-[#4B4B4B] mb-4">Last updated: October 14, 2023</p>

          <p className="text-[#4B4B4B] mb-4">
            This Privacy Policy describes Our policies and procedures on the collection, use and
            disclosure of Your information when You use the Service and tells You about Your privacy
            rights and how the law protects You.
          </p>

          <p className="text-[#4B4B4B] mb-6">
            We use Your Personal data to provide and improve the Service. By using the Service, You
            agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-semibold text-brand mb-3">Interpretation and Definitions</h2>

          <h3 className="text-xl font-medium text-brand mb-2">Interpretation</h3>
          <p className="text-[#4B4B4B] mb-4">
            The words of which the initial letter is capitalized have meanings defined under the
            following conditions. The following definitions shall have the same meaning regardless of
            whether they appear in singular or in plural.
          </p>

          <h3 className="text-xl font-medium text-brand mb-2">Definitions</h3>
          <p className="text-[#4B4B4B] mb-3">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc ml-6 space-y-2 text-[#4B4B4B] mb-6">
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service
              or parts of our Service.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in
              this Agreement) refers to Arjava India Tech Pvt Ltd, 19 Ganesh Nagar Main Road,
              Selaiyur, Chennai - 600073.
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of Your browsing
              history on that website among its many uses.
            </li>
            <li>
              <strong>Country</strong> refers to: Tamil Nadu, India.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person who processes the
              data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by
              the use of the Service or from the Service infrastructure itself.
            </li>
            <li>
              <strong>Website</strong> refers to Arjava, accessible from{' '}
              <a
                href="https://arjavatech.com"
                target="_blank"
                rel="noreferrer"
                className="text-blue-600 underline"
              >
                https://arjavatech.com
              </a>
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the Service.
            </li>
          </ul>

          <h2 className="text-2xl font-semibold text-brand mb-3">
            Collecting and Using Your Personal Data
          </h2>

          <h3 className="text-xl font-medium text-brand mb-2">Types of Data Collected</h3>

          <h4 className="text-lg font-medium text-brand mb-2">Personal Data</h4>
          <p className="text-[#4B4B4B] mb-3">
            While using Our Service, We may ask You to provide Us with certain personally
            identifiable information that can be used to contact or identify You. Personally
            identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc ml-6 space-y-1 text-[#4B4B4B] mb-6">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-medium text-brand mb-2">Usage Data</h4>
          <p className="text-[#4B4B4B] mb-6">
            Usage Data is collected automatically when using the Service. Usage Data may include
            information such as Your Device's Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>

          <h3 className="text-xl font-medium text-brand mb-2">Use of Your Personal Data</h3>
          <p className="text-[#4B4B4B] mb-3">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="list-disc ml-6 space-y-2 text-[#4B4B4B] mb-6">
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account as a registered user of the Service.</li>
            <li>For the performance of a contract.</li>
            <li>To contact You with updates or informative communications.</li>
            <li>To provide You with news, special offers and general information.</li>
            <li>To manage Your requests to Us.</li>
          </ul>

          <h3 className="text-xl font-medium text-brand mb-2">Contact Us</h3>
          <p className="text-[#4B4B4B] mb-2">
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <ul className="list-disc ml-6 space-y-1 text-[#4B4B4B]">
            <li>
              By email:{' '}
              <a href="mailto:arjavatech@gmail.com" className="text-blue-600 underline">
                arjavatech@gmail.com
              </a>
            </li>
            <li>By phone: 044-35675035</li>
          </ul>
        </div>
      </div>

      <br />
      <Footer />
    </>
  )
}
